[package]
name = "timeagoplus"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
chrono = "0.4"
lazy_static = "1.4.0" # Use the latest version from crates.io
[lib]
crate-type = ["cdylib", "rlib"]